version: '2'

services:
    mysql:
        image: mysql
        restart: always
        env_file:
           - variables.env
        # volumes:
        #     - ./data/mysql:/docker-entrypoint-initdb.d
    nginx:
        depends_on:
            - phpfpm
        image: nginx
        ports:
            - "80:80"
        restart: always
        working_dir: /var/www
        volumes:
            - ./phalcon:/var/www/
            - ./conf/nginx/phalcon.conf:/etc/nginx/conf.d/default.conf
        links:
            - phpfpm
    
    phpfpm:
        image: phalconphp/php-apache:ubuntu-16.04
        restart: always
        working_dir: /var/www
        ports:
            - "8080:80"
        volumes:
            - ./phalcon:/var/www
            - ./conf/php/fpm.ini://etc/php/7.0/fpm/php.ini
        depends_on:
            - mysql
    composer:
        restart: 'no'
        image: phalconphp/composer
        command: install --no-dev
        working_dir: /var/www
        volumes:
            - ./phalcon:/var/www
    

volumes:
  mysql:
    driver: local

